/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './src/pages/**/*.{js,jsx}',
    './src/components/**/*.{js,jsx}',
    './src/app/**/*.{js,jsx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'primary':                   '#00153e',
        'primary-container':         '#002867',
        'on-primary':                '#ffffff',
        'on-primary-container':      '#6390f7',
        'primary-fixed':             '#dae2ff',
        'primary-fixed-dim':         '#b1c5ff',
        'on-primary-fixed':          '#001946',
        'inverse-primary':           '#b1c5ff',
        'secondary':                 '#48626e',
        'secondary-container':       '#cbe7f5',
        'secondary-fixed':           '#cbe7f5',
        'secondary-fixed-dim':       '#afcbd8',
        'on-secondary':              '#ffffff',
        'on-secondary-container':    '#4e6874',
        'on-secondary-fixed':        '#021f29',
        'on-secondary-fixed-variant':'#304a55',
        'tertiary':                  '#001d06',
        'tertiary-container':        '#003410',
        'tertiary-fixed':            '#69ff87',
        'tertiary-fixed-dim':        '#3ce36a',
        'on-tertiary':               '#ffffff',
        'on-tertiary-container':     '#00aa45',
        'on-tertiary-fixed':         '#002108',
        'on-tertiary-fixed-variant': '#00531e',
        'surface':                   '#f7f9fc',
        'surface-bright':            '#f7f9fc',
        'surface-dim':               '#d8dadd',
        'surface-container':         '#eceef1',
        'surface-container-low':     '#f2f4f7',
        'surface-container-lowest':  '#ffffff',
        'surface-container-high':    '#e6e8eb',
        'surface-container-highest': '#e0e3e6',
        'on-surface':                '#191c1e',
        'on-surface-variant':        '#43474f',
        'surface-tint':              '#2559bd',
        'inverse-surface':           '#2d3133',
        'inverse-on-surface':        '#eff1f4',
        'outline':                   '#747780',
        'outline-variant':           '#c4c6d0',
        'error':                     '#ba1a1a',
        'error-container':           '#ffdad6',
        'on-error':                  '#ffffff',
        'on-error-container':        '#93000a',
        'background':                '#f7f9fc',
        'on-background':             '#191c1e',
      },
      fontFamily: {
        'headline': ['Manrope', 'sans-serif'],
        'body':     ['Inter',   'sans-serif'],
        'label':    ['Inter',   'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg:  '0.5rem',
        xl:  '0.75rem',
        '2xl': '1rem',
        '3xl': '1.25rem',
        full: '9999px',
      },
    },
  },
  plugins: [],
};
